### ISSUE TITLE
Scooped and bright sound in a mix.

### ISSUE THREAD

**Issue by 38github** [resonantdsp/SwankyAmp#16]
Not really a bug issue per say but I find it hard to get out the scooped sound and its bright sound. It sounds as if it has notch somewhere between 300-600 Hz that makes it hard to mixit with other amp sounds. I also need to lower all treble, bright and presence controls to play well with other sounds. Alone it is amazing.

**Comment by gmcgoldr** [comment]
There's been some voicing changes in version 0.7.2 I believe, so you might get something more to your liking. However that scoop is probably the result of the tone stack being loosely based on the fender tone stack which has quite a deep mids scoop. I might look into adding more tone stack variants later. Thanks for the feedback.
