### ISSUE TITLE
Swankyamp 0.9 to rumble over time.

### ISSUE THREAD

**Issue by 38github** [resonantdsp/SwankyAmp#26]
I have found another bug (Reaper, Windows) that presents itself after using Swankyamp for a while. A low rumble starts to build up which after about thirty minutes stops and instead it sounds like low frequency bursts. This time I used the plugin at 96000Hz and I haven't tried this at 48000Hz like the last time I reported a "time duration bug".

![swankyamp_09_reaper_rumble_amp](https://user-images.githubusercontent.com/18294149/89714080-7c320580-d99c-11ea-87a8-94db5c683464.png)
![swankyamp_09_reaper_rumble_waveform](https://user-images.githubusercontent.com/18294149/89714084-7fc58c80-d99c-11ea-94fd-68f1b31c30d5.png)

Audio file: https://easyupload.io/j1mqzu

**Comment by gmcgoldr** [comment]
I'll have a look ASAP again. I immediately suspect the low pass again, but who knows. Thanks for finding this, I'll do a bit more stability testing next time, would really like to get this algorithm to be properly reliable.

**Comment by 38github** [comment]
No problem. I really like this plugin and its character so I will report every bug I will stumble upon.

**Comment by 38github** [comment]
Any luck finding the source of the problem?

**Comment by gmcgoldr** [comment]
It's a tricky one. I managed to reproduce it but only under narrow circumstances: if the plugin is running with zero input (not just really quiet, but actually a stream of 0s) the issue doesn't arise. With more substantial input it also doesn't seem to arise. But when recording just low level noise I was able to see this behavior.

I don't know for sure what is the culprit but I'm embarking on a refactor of the way the DSP code is handled to avoid such instabilities and to make debugging easier.

**Comment by guitarzan** [comment]
Hey, glad to see you're still working on Swanky Amp! I was just wondering what was up — it's been a while.

**Comment by gmcgoldr** [comment]
There's a new update out which might address this issue. There was a major rework of the DSP pipeline to avoid such issues. In my testing the amp ran with no change in sound for over 30 minutes. But beyond this I can't confirm with certainty that the issue is fully resolved.

**Comment by gmcgoldr** [comment]
Things seem pretty stable since 0.10.0, I'll mark this closed.
